settings:
  cosmos_name: xia-cosmos
  cosmos_project: xia-cosmos
  cosmos_org: x-i-a.com
  github_owner: x-i-a
  github_tpl_owner: x-i-a
  github_tpl_foundation: xia-template-foundation
structure:
  realms:
    protocol:
      foundations:
        xia-framework:
          repository: xia-foundation-framework
cicd: github
environments:
  prd:
    match_branch: refs/heads/main
    stages:
    - deploy
    - local-test
    - remote-test
    - publish
