git: github
topology:
  type: gcp
settings:
  cosmos_name: xia-cosmos
  cosmos_project: xia-cosmos
  bucket_name: xia-cosmos
  bucket_region: eu
foundations:
  default_visibility: public
  default_owner: x-i-a
  default_tpl_owner: x-i-a
  default_tpl_name: xia-template-foundation
structure:
  realms:
    protocol:
      foundations:
        xia-framework:
          repository_name: xia-foundation-framework
          repository: xia-foundation-framework
    test:
      foundations:
        xia-test:
          repository_name: xia-foundation-test
          repository: xia-foundation-framework
