settings:
  cosmos_name: xia-cosmos
  realm_name: xia-governance
  foundation_name: xia-framework
  foundation_region: eu
  github_owner: x-i-a
  pip_index_url: https://europe-west1-python.pkg.dev/xia-framework-prd/pypi/simple
