xia-module:
  package: xia-module
  class: Module
gcp-module-organization:
  package: xia-module-gcp-project
  class: Organization
  events:
    deploy:
gh-module-foundation:
  package: xia-module-application-gh
  class: Foundation
  events:
    deploy:
module-state-gcs:
  package: xia-module-terraform-gcs
  class: GcsState
  events:
    activate:
